# Generated by Django 5.0 on 2025-11-14 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='duration_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric')], max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('INVESTMENT', 'Investment')], default='EXPENSE', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GROCERY', 'Grocery'), ('FUEL', 'Vehicle Fuel'), ('BANK_FD', 'Bank FD'), ('BANK_LOAN', 'Bank Loan'), ('BANK_ACCOUNT', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('INSURANCE', 'Insurance'), ('INVESTMENT', 'Investment')], max_length=20),
        ),
    ]
