# Generated by Django 5.0 on 2025-11-14 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0002_bill_account_number_bill_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='liters',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GROCERY', 'Grocery')], max_length=20),
        ),
    ]
