# Generated by Django 5.0 on 2025-11-18 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0003_remove_bill_account_number_remove_bill_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date', '-due_date']},
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bill',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum payment required', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bill',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance for loans/credit cards', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GROCERY', 'Grocery'), ('PHONE', 'Phone Bill'), ('WIFI', 'WiFi Bill'), ('LOAN', 'Loan Payment'), ('CREDIT_CARD', 'Credit Card Payment')], max_length=20),
        ),
    ]
