# Generated by Django 5.0 on 2025-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0004_alter_bill_options_bill_due_date_bill_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='minimum_payment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='outstanding_balance',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GROCERY', 'Grocery')], max_length=20),
        ),
    ]
