# Generated by Django 5.0 on 2025-11-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0005_alter_bill_options_remove_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GROCERY', 'Grocery'), ('BANKING', 'Banking'), ('LOAN', 'Loan Payment'), ('CREDIT_CARD', 'Credit Card Payment'), ('PHONE', 'Phone Bill'), ('WIFI', 'WiFi Bill'), ('FUEL', 'Fuel'), ('VEHICLE_REPAIR', 'Vehicle Repairs'), ('OTHER', 'Other Expenses')], max_length=20),
        ),
    ]
