# Generated by Django 5.0 on 2026-02-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills_api', '0007_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
